### ISSUE TITLE
Two titles inside head tag

### ISSUE THREAD

**Issue by pmviva** [curttimson/hugo-theme-massively#12]
The htmlhead.html partial outputs two titles in the head tag

```
<title>{{ if not .IsHome }} {{ .Title }} &middot; {{ end }} {{ .Site.Title }}</title>
<title>{{ .Title }}</title>
```
A possible fix is to make the partial output the following:

```
<title>{{ if eq (.Title) (.Site.Title) }}{{ .Site.Title }}{{ else }}{{ .Title }} &middot; {{ .Site.Title }}{{ end }}</title>
```

**Comment by curttimson** [comment]
Thanks for raising the issue and providing a fix.

I've merged these changes in now so closing the issue

https://github.com/curttimson/hugo-theme-massively/pull/13
