### ISSUE TITLE
Use absURL and relURL functions instead of BaseURL

### ISSUE THREAD

**Issue by pmviva** [curttimson/hugo-theme-massively#14]
Use the absURL and relURL functions provided by Hugo instead of concatenating the site variable {{ .Site.BaseURL }} since concatenation is more error prone.

**Comment by pmviva** [comment]
It also allows a nice transition in the future to enable multilingual mode just replacing absURL with absLangURL and relURL with relLangURL.

**Comment by curttimson** [comment]
Closing thanks to: https://github.com/curttimson/hugo-theme-massively/pull/16
