### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by pmviva** [curttimson/hugo-theme-massively#15]
I propose adding multilingual support to the theme, since Hugo provides multilingual mode since a long time ago.

As far as I have seen there are not much strings to translate.

The theme should:

1.  Provide a i18n folder with default translations for English (and possibly Spanish since is my native language)
2. Use absLangURL and relLangURL functions provided by Hugo
3. Add links to current page translations if any in the in the navigation bar 
4. Adapt the example site to provide a multilingual configuration for testing

I can make a pull request with the changes if you are OK with it.

**Comment by curttimson** [comment]
@pmviva This sounds great!

If you're happy to create a PR I'll be more than happy to review.

**Comment by pmviva** [comment]
Sure, I'll find some time in the week to implement the changes.
