### ISSUE TITLE
 Paginate: 'pager size' must be a positive integer

### ISSUE THREAD

**Issue by nsewolo** [curttimson/hugo-theme-massively#26]
Hild sites returns avery time the same error: 
Building sites … ERROR 2018/04/12 22:03:45 Error while rendering "home" in "": template: index.html:15:21: executing "index.html" at <.Paginate>: error calling Paginate: 'pager size' must be a positive integer

**Comment by pierrepln** [comment]
Hi @utnas ,  I solved the same error right affter installing the theme.
The reason I had this error was because I forgot to edit the `config.toml` file at the root of your project.

It requires ```[params.posts]
    foldername = "post"
    pagesize = "6"
    featuredpost = "true"
``` 

I hope this helps

**Comment by curttimson** [comment]
This should be configured to be optional ideally to make the theme more portable.
