### ISSUE TITLE
Hardcoded Google Analytics tag, and internal templates

### ISSUE THREAD

**Issue by shortword** [curttimson/hugo-theme-massively#37]
While debugging an issue I found that the Google Analytics (GA) partial includes a hardcoded tag. This seems like it might be something leftover from initial development, or debugging.
[hugo-theme-massively/layouts/partials/scripts/googleanalytics.html - Line 3](https://github.com/curttimson/hugo-theme-massively/blob/master/layouts/partials/scripts/googleanalytics.html#L3)

When investigating a fix for this I found that Hugo provides internal templates for GA. As an added bonus they have updated these recently to maintain GDPR compliance. So, if we can leverage these it is less work for us long term.

(I found this while looking in to issues I was seeing with Disqus which has a similar template available. That said, there will likely be some discussion on handling that, so I'll file another issue for it.)

Mike

**Comment by shortword** [comment]
I semi-accidentally/prematurely submitted my pull request. Oh well, it is available here: https://github.com/curttimson/hugo-theme-massively/pull/36

:)

**Comment by curttimson** [comment]
Closing as #36 has been merged
