### ISSUE TITLE
Enhancement: Utilize Hugo's disqus template

### ISSUE THREAD

**Issue by shortword** [curttimson/hugo-theme-massively#38]
In the same vein as [issue 37](https://github.com/curttimson/hugo-theme-massively/issues/37), I noticed that Hugo provides an internal disqus template which, if we aligned with it, would make maintenance life easier in the long run.

However, using this template diverges a bit from the previous behavior of the package. Previously, disqus would only show up in massively if the front matter included a 'disqusid'. This differs from how Hugo handles it internally, as well as other packages I've used for Jekyll and Wordpress, which all show it on every post/blog page unless otherwise turned off. If nothing else I'd push for alignment with Hugo as being the driving factor for this proposed change.

As with my other filed issue, I've created a branch in my fork and will submit a pull request for review. Please let me know if you have any questions or concerns.

Mike

**Comment by shortword** [comment]
See pull request: https://github.com/curttimson/hugo-theme-massively/pull/39

**Comment by curttimson** [comment]
#39 has now been merged to `master`
