### ISSUE TITLE
Help Adding Menu Items

### ISSUE THREAD

**Issue by fernando-mc** [curttimson/hugo-theme-massively#41]
Hello!

Apologies if this is documented somewhere already, but could you let me know if there is something different I should be doing to add items to the menu for this theme? From what I can tell these are generated in nav.html here - https://github.com/curttimson/hugo-theme-massively/blob/master/layouts/partials/nav.html

Normally, to add an item to the top level menu of a Hugo theme I think I would add some config in the config.toml file that let's me set some menus and refer to pages such as /about or another external link.

Is there currently a way to do this? It seems like the menu items will appear for multi-language sites but I'm wondering what the simplest way to just add a new link to a page or external link might be.

Thanks!

**Comment by curttimson** [comment]
Hi @fernando-mc 

This feature doesn't currently exist for this theme, however it's a great suggestion!

Feel free to raise a PR, or I'll see if I can find time to add this feature myself :)

Thanks

**Comment by fernando-mc** [comment]
@curttimson sounds good. I opened a PR here - https://github.com/curttimson/hugo-theme-massively/pull/48

**Comment by fernando-mc** [comment]
@curttimson I'll go ahead and close this since I implemented a fix for my own purposes that might not align completely with the multi-language features. Feel free to use whatever you think makes sense from #48!
