### ISSUE TITLE
Date is still shown when unset

### ISSUE THREAD

**Issue by Smirl** [curttimson/hugo-theme-massively#50]
When the date is not set in Front Matter it is set to 0.

In the site this shows as `January 1st, 0001` when the templates have the intention to hide the date when it is "false".

I will raise a PR to fix this with the answer outlined in this post: https://discourse.gohugo.io/t/show-content-if-date-is-set-in-frontmatter/1974

The files that need to be changed are:
* layouts/_default/single.html
* layouts/partials/posts/featured.html
* layouts/partials/posts/list.html

**Comment by curttimson** [comment]
Closing issue as #51 has been merged to master as part of Release 4.2.1
