### ISSUE TITLE
Massively Demo on Hugo website contains 3rd party tracking

### ISSUE THREAD

**Issue by onedrawingperday** [curttimson/hugo-theme-massively#54]
Hello again @curttimson 

Same as your [other theme](https://github.com/curttimson/hugo-theme-dopetrope/issues/38) this theme's demo also has third party tracking enabled.

```
     \hugo-theme-massively\exampleSite\config.toml:
        googleanalytics = "UA-113904582-3"
        disqusShortname = "hugo-massively"
```

To fix this issue please leave the above parameters blank i.e.

```
     \hugo-theme-massively\exampleSite\config.toml:
        googleanalytics = ""
        disqusShortname = ""
```

Once you look into this please let me know.

Thank you!

ref: https://github.com/gohugoio/hugoThemes/issues/535

**Comment by curttimson** [comment]
https://github.com/gohugoio/hugoThemes/issues/535

**Comment by onedrawingperday** [comment]
Thank you for the fix.
